[package]
name = "temporal-fmt"
version = "0.1.1"
authors = ["Jan Roman Cisowski <code@cisowscy.com>"]
description = "A lightweight, standalone UNIX timestamp formatter with advanced seasonal and astronomical tokens."
repository = "https://github.com/j-Cis/temporal-fmt"
readme = "README.md"
keywords = [
    "time",
    "timestamp",
    "format",
    "date",
    "unix"
]
categories = [
    "date-and-time",
    "value-formatting",
    "no-std"
]
license = "Unlicense OR MIT"
edition = "2024"
rust-version = "1.96.0"
resolver = "3"

include = [
    "src/**/*",
    "examples/**/*",
    "Cargo.toml",
    "README.md",
    "LICENSE*",
]

[package.metadata.cargo]
edition = "2024"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
targets = [
    "x86_64-pc-windows-msvc",
    "i686-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "i686-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin"
]


[badges]
travis-ci = { repository = "j-Cis/temporal-fmt" }
appveyor = { repository = "j-Cis/temporal-fmt" }

[dependencies]